repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        files: ^(communication-node|configurator)/.*\.py$

-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        args: [--max-line-length=100, --statistics]
        files: ^(communication-node|configurator)/.*\.py$

-   repo: https://github.com/PyCQA/pylint
    rev: v3.3.4
    hooks:
    -   id: pylint
        files: ^(communication-node|configurator)/.*\.py$
        additional_dependencies:
          - pytest
          - flask
          - requests
          - psycopg2

-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    -   id: clang-format
        args: [--style=file:./esp32-software/.clang-format]
        files: ^esp32-software/.*\.(c|h)$
    -   id: cppcheck
        args: [
            "--suppress=missingIncludeSystem",
            "--suppress=unusedFunction",
            "--suppress=unusedStructMember",
            "-Iesp32-software/components/config_server/include",
            "-Iesp32-software/components/config_storage/include",
            "-Iesp32-software/components/wifi_manager/include",
            "--inline-suppr",
            "--enable=style,warning,performance,portability",
            "--check-level=exhaustive",
            "--language=c",
            "--error-exitcode=1"
        ]
        files: ^esp32-software/.*$

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
