---
config:
  theme: base
---
classDiagram
    class Location {
        -id: unique int
        -city: string
        -street: string
        -apartment: string
        -floor: string
        -number: int
        +getLocation()
    }
    class Microcontroller {
        -id: unique int
        -name: string
        -motionSensor: bool
        -soundSensor: bool
        -gasSensor: bool
        -esp32_identifier: hash
        -business: Business
        +sendData()
        +toggleSensor(string)
    }
    class Business {
        -id: unique int
        -name: string
        -location: Location
        -phone: string
        +getName()
        +validateIdentifier(string)
        +getEvents()
    }
    Location --* Business
    class EventType {
        -id: unique int
        -name: string
        -level: int
        getName()
        getLevel()
    }
    class Event {
        -id: unique int
        -type: EventType
        -date: datetime
        -microcontroller: Microcontroller
        +alertAuthorities()
        +alertSupportTeam()
    }
    EventType --o Event
    Event --* Microcontroller
    Microcontroller --* Business
